### ISSUE TITLE
Typo in indices 

### ISSUE THREAD

**Issue by eamaldi** [arendMoerman/MockSZ#4]
https://github.com/arend95/MockSZ/blob/6f76eadc636fbc69473cac58ddd9831fe175528b/src/MockSZ/SinglePointing.py#L72C33-L72C33

In the function GetSpecIntensity, the step size ds always equals 0. As far as I can tell, ds is only used to offset the S axis of the S-NU grid by half a step, which is likely why this hasn't caused any noticeable problems. To fix this, simply change "ds = s_range[1] - s_range[1]" to "ds = s_range[1] - s_range[0]"

**Comment by arendMoerman** [comment]
Typo corrected in commit 6ac0da0
